---
- name: Install Apache
  apt:
    name: apache2
    state: present
  notify: Start Apache

- name: Deploy web application
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: true

# Handlers should be defined in a separate section
