---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true

- name: Create a database for the web application
  mysql_db:
    name: webapp_db
    state: present
    login_user: ansible
    login_password: raja
